[workspace]

members = [
    "crates/*",
    "crates/bpe/benchmarks",
    "crates/bpe/tests",
    "crates/posting-list/benchmarks",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true