[workspace]

members = [
    "crates/*",
    "crates/bpe/benchmarks",
    "crates/bpe/bindings/python",
    "crates/bpe/tests",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true
