# save report in this directory, even if a custom target directory is set
criterion_home = "./target/criterion"

# The colors table allows users to configure the colors used by the charts 
# cargo-criterion generates.
[colors]
# Color-blind friendly color scheme from https://personal.sron.nl/~pault/.
comparison_colors = [
  {r =  51, g =  34, b = 136 }, # indigo
  {r = 136, g = 204, b = 238 }, # cyan
  {r =  68, g = 170, b = 153 }, # teal
  {r =  17, g = 119, b =  51 }, # green
  {r = 153, g = 153, b =  51 }, # olive
  {r = 221, g = 204, b = 119 }, # sand
  {r = 204, g = 102, b = 119 }, # rose
  {r = 136, g =  34, b =  85 }, # wine
  {r = 170, g =  68, b = 153 }, # purple
]
