# Consider adding "--codegen=link-args=-Wl,--compress-debug-sections=zlib"

[target.x86_64-unknown-linux-gnu]
# SSE3 is requred by simd-varint.
# POPCNT makes `count_ones` (which we use in geofilter and bitrank) more efficient.
rustflags = ["-C", "target-feature=+ssse3,+avx2,+popcnt"]

[target.x86_64-apple-darwin]
# SSE3 is requred by simd-varint.
# POPCNT makes `count_ones` (which we use in geofilter and bitrank) more efficient.
rustflags = ["-C", "target-feature=+ssse3,+avx2,+popcnt"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon"]
