[target.x86_64-unknown-linux-gnu]
# SSE3 is requred by simd-varint. tokio_unstable is for tokio-console.
rustflags = ["-C", "target-feature=+ssse3,+avx2,+avx512,+popcnt,+bmi2", "--cfg", "tokio_unstable"]

[target.x86_64-apple-darwin]
# SSE3 is requred by simd-varint. tokio_unstable is for tokio-console.
rustflags = ["-C", "target-feature=+ssse3,+avx2,+bmi2", "--cfg", "tokio_unstable"]